<?php
/**
 * InstancesEducationOrganizationsStateEducationAgenciesApi
 * PHP version 7.4
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EdGraph\PlatformClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use EdGraph\PlatformClient\ApiException;
use EdGraph\PlatformClient\Configuration;
use EdGraph\PlatformClient\HeaderSelector;
use EdGraph\PlatformClient\ObjectSerializer;

/**
 * InstancesEducationOrganizationsStateEducationAgenciesApi Class Doc Comment
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InstancesEducationOrganizationsStateEducationAgenciesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createStateEducationAgencyAsync' => [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'deleteStateEducationAgencyAsync' => [
            'application/json',
        ],
        'getStateEducationAgencyByIdAsync' => [
            'application/json',
        ],
        'updateStateEducationAgencyAsync' => [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/*+json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createStateEducationAgencyAsync
     *
     * Creates a StateEducationAgency.
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  \EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest $edfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStateEducationAgencyAsync'] to see the possible values for this operation
     *
     * @throws \EdGraph\PlatformClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1StateEducationAgencyCreatedResponse|\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails
     */
    public function createStateEducationAgencyAsync($tenantId, $instanceId, $year, $edfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest = null, string $contentType = self::contentTypes['createStateEducationAgencyAsync'][0])
    {
        list($response) = $this->createStateEducationAgencyAsyncWithHttpInfo($tenantId, $instanceId, $year, $edfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest, $contentType);
        return $response;
    }

    /**
     * Operation createStateEducationAgencyAsyncWithHttpInfo
     *
     * Creates a StateEducationAgency.
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  \EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest $edfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStateEducationAgencyAsync'] to see the possible values for this operation
     *
     * @throws \EdGraph\PlatformClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1StateEducationAgencyCreatedResponse|\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function createStateEducationAgencyAsyncWithHttpInfo($tenantId, $instanceId, $year, $edfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest = null, string $contentType = self::contentTypes['createStateEducationAgencyAsync'][0])
    {
        $request = $this->createStateEducationAgencyAsyncRequest($tenantId, $instanceId, $year, $edfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 401:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 201:
                    if ('\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1StateEducationAgencyCreatedResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1StateEducationAgencyCreatedResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1StateEducationAgencyCreatedResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1StateEducationAgencyCreatedResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1StateEducationAgencyCreatedResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createStateEducationAgencyAsyncAsync
     *
     * Creates a StateEducationAgency.
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  \EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest $edfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStateEducationAgencyAsync'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createStateEducationAgencyAsyncAsync($tenantId, $instanceId, $year, $edfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest = null, string $contentType = self::contentTypes['createStateEducationAgencyAsync'][0])
    {
        return $this->createStateEducationAgencyAsyncAsyncWithHttpInfo($tenantId, $instanceId, $year, $edfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createStateEducationAgencyAsyncAsyncWithHttpInfo
     *
     * Creates a StateEducationAgency.
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  \EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest $edfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStateEducationAgencyAsync'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createStateEducationAgencyAsyncAsyncWithHttpInfo($tenantId, $instanceId, $year, $edfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest = null, string $contentType = self::contentTypes['createStateEducationAgencyAsync'][0])
    {
        $returnType = '\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1StateEducationAgencyCreatedResponse';
        $request = $this->createStateEducationAgencyAsyncRequest($tenantId, $instanceId, $year, $edfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createStateEducationAgencyAsync'
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  \EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest $edfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createStateEducationAgencyAsync'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createStateEducationAgencyAsyncRequest($tenantId, $instanceId, $year, $edfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest = null, string $contentType = self::contentTypes['createStateEducationAgencyAsync'][0])
    {

        // verify the required parameter 'tenantId' is set
        if ($tenantId === null || (is_array($tenantId) && count($tenantId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenantId when calling createStateEducationAgencyAsync'
            );
        }

        // verify the required parameter 'instanceId' is set
        if ($instanceId === null || (is_array($instanceId) && count($instanceId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $instanceId when calling createStateEducationAgencyAsync'
            );
        }

        // verify the required parameter 'year' is set
        if ($year === null || (is_array($year) && count($year) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $year when calling createStateEducationAgencyAsync'
            );
        }



        $resourcePath = '/tenants/{tenantId}/edfiadmin/instances/{instanceId}/years/{year}/stateeducationagencies';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($tenantId !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenantId),
                $resourcePath
            );
        }
        // path params
        if ($instanceId !== null) {
            $resourcePath = str_replace(
                '{' . 'instanceId' . '}',
                ObjectSerializer::toPathValue($instanceId),
                $resourcePath
            );
        }
        // path params
        if ($year !== null) {
            $resourcePath = str_replace(
                '{' . 'year' . '}',
                ObjectSerializer::toPathValue($year),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($edfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($edfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest));
            } else {
                $httpBody = $edfiAdminApiEdfiAdminV1CreateStateEducationAgencyRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteStateEducationAgencyAsync
     *
     * Deletes a StateEducationAgency.
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  string $stateEducationAgencyId  (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteStateEducationAgencyAsync'] to see the possible values for this operation
     *
     * @throws \EdGraph\PlatformClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteStateEducationAgencyAsync($tenantId, $instanceId, $year, $stateEducationAgencyId, string $contentType = self::contentTypes['deleteStateEducationAgencyAsync'][0])
    {
        $this->deleteStateEducationAgencyAsyncWithHttpInfo($tenantId, $instanceId, $year, $stateEducationAgencyId, $contentType);
    }

    /**
     * Operation deleteStateEducationAgencyAsyncWithHttpInfo
     *
     * Deletes a StateEducationAgency.
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  string $stateEducationAgencyId  (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteStateEducationAgencyAsync'] to see the possible values for this operation
     *
     * @throws \EdGraph\PlatformClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteStateEducationAgencyAsyncWithHttpInfo($tenantId, $instanceId, $year, $stateEducationAgencyId, string $contentType = self::contentTypes['deleteStateEducationAgencyAsync'][0])
    {
        $request = $this->deleteStateEducationAgencyAsyncRequest($tenantId, $instanceId, $year, $stateEducationAgencyId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteStateEducationAgencyAsyncAsync
     *
     * Deletes a StateEducationAgency.
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  string $stateEducationAgencyId  (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteStateEducationAgencyAsync'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteStateEducationAgencyAsyncAsync($tenantId, $instanceId, $year, $stateEducationAgencyId, string $contentType = self::contentTypes['deleteStateEducationAgencyAsync'][0])
    {
        return $this->deleteStateEducationAgencyAsyncAsyncWithHttpInfo($tenantId, $instanceId, $year, $stateEducationAgencyId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteStateEducationAgencyAsyncAsyncWithHttpInfo
     *
     * Deletes a StateEducationAgency.
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  string $stateEducationAgencyId  (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteStateEducationAgencyAsync'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteStateEducationAgencyAsyncAsyncWithHttpInfo($tenantId, $instanceId, $year, $stateEducationAgencyId, string $contentType = self::contentTypes['deleteStateEducationAgencyAsync'][0])
    {
        $returnType = '';
        $request = $this->deleteStateEducationAgencyAsyncRequest($tenantId, $instanceId, $year, $stateEducationAgencyId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteStateEducationAgencyAsync'
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  string $stateEducationAgencyId  (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteStateEducationAgencyAsync'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteStateEducationAgencyAsyncRequest($tenantId, $instanceId, $year, $stateEducationAgencyId, string $contentType = self::contentTypes['deleteStateEducationAgencyAsync'][0])
    {

        // verify the required parameter 'tenantId' is set
        if ($tenantId === null || (is_array($tenantId) && count($tenantId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenantId when calling deleteStateEducationAgencyAsync'
            );
        }

        // verify the required parameter 'instanceId' is set
        if ($instanceId === null || (is_array($instanceId) && count($instanceId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $instanceId when calling deleteStateEducationAgencyAsync'
            );
        }

        // verify the required parameter 'year' is set
        if ($year === null || (is_array($year) && count($year) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $year when calling deleteStateEducationAgencyAsync'
            );
        }

        // verify the required parameter 'stateEducationAgencyId' is set
        if ($stateEducationAgencyId === null || (is_array($stateEducationAgencyId) && count($stateEducationAgencyId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $stateEducationAgencyId when calling deleteStateEducationAgencyAsync'
            );
        }


        $resourcePath = '/tenants/{tenantId}/edfiadmin/instances/{instanceId}/years/{year}/stateeducationagencies/{stateEducationAgencyId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($tenantId !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenantId),
                $resourcePath
            );
        }
        // path params
        if ($instanceId !== null) {
            $resourcePath = str_replace(
                '{' . 'instanceId' . '}',
                ObjectSerializer::toPathValue($instanceId),
                $resourcePath
            );
        }
        // path params
        if ($year !== null) {
            $resourcePath = str_replace(
                '{' . 'year' . '}',
                ObjectSerializer::toPathValue($year),
                $resourcePath
            );
        }
        // path params
        if ($stateEducationAgencyId !== null) {
            $resourcePath = str_replace(
                '{' . 'stateEducationAgencyId' . '}',
                ObjectSerializer::toPathValue($stateEducationAgencyId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getStateEducationAgencyByIdAsync
     *
     * Retrieves a StateEducationAgency by ID.
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  string $stateEducationAgencyId  (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStateEducationAgencyByIdAsync'] to see the possible values for this operation
     *
     * @throws \EdGraph\PlatformClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1StateEducationAgency|\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails
     */
    public function getStateEducationAgencyByIdAsync($tenantId, $instanceId, $year, $stateEducationAgencyId, string $contentType = self::contentTypes['getStateEducationAgencyByIdAsync'][0])
    {
        list($response) = $this->getStateEducationAgencyByIdAsyncWithHttpInfo($tenantId, $instanceId, $year, $stateEducationAgencyId, $contentType);
        return $response;
    }

    /**
     * Operation getStateEducationAgencyByIdAsyncWithHttpInfo
     *
     * Retrieves a StateEducationAgency by ID.
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  string $stateEducationAgencyId  (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStateEducationAgencyByIdAsync'] to see the possible values for this operation
     *
     * @throws \EdGraph\PlatformClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1StateEducationAgency|\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function getStateEducationAgencyByIdAsyncWithHttpInfo($tenantId, $instanceId, $year, $stateEducationAgencyId, string $contentType = self::contentTypes['getStateEducationAgencyByIdAsync'][0])
    {
        $request = $this->getStateEducationAgencyByIdAsyncRequest($tenantId, $instanceId, $year, $stateEducationAgencyId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 401:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 200:
                    if ('\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1StateEducationAgency' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1StateEducationAgency' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1StateEducationAgency', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1StateEducationAgency';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1StateEducationAgency',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getStateEducationAgencyByIdAsyncAsync
     *
     * Retrieves a StateEducationAgency by ID.
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  string $stateEducationAgencyId  (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStateEducationAgencyByIdAsync'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStateEducationAgencyByIdAsyncAsync($tenantId, $instanceId, $year, $stateEducationAgencyId, string $contentType = self::contentTypes['getStateEducationAgencyByIdAsync'][0])
    {
        return $this->getStateEducationAgencyByIdAsyncAsyncWithHttpInfo($tenantId, $instanceId, $year, $stateEducationAgencyId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getStateEducationAgencyByIdAsyncAsyncWithHttpInfo
     *
     * Retrieves a StateEducationAgency by ID.
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  string $stateEducationAgencyId  (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStateEducationAgencyByIdAsync'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getStateEducationAgencyByIdAsyncAsyncWithHttpInfo($tenantId, $instanceId, $year, $stateEducationAgencyId, string $contentType = self::contentTypes['getStateEducationAgencyByIdAsync'][0])
    {
        $returnType = '\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1StateEducationAgency';
        $request = $this->getStateEducationAgencyByIdAsyncRequest($tenantId, $instanceId, $year, $stateEducationAgencyId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getStateEducationAgencyByIdAsync'
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  string $stateEducationAgencyId  (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getStateEducationAgencyByIdAsync'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getStateEducationAgencyByIdAsyncRequest($tenantId, $instanceId, $year, $stateEducationAgencyId, string $contentType = self::contentTypes['getStateEducationAgencyByIdAsync'][0])
    {

        // verify the required parameter 'tenantId' is set
        if ($tenantId === null || (is_array($tenantId) && count($tenantId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenantId when calling getStateEducationAgencyByIdAsync'
            );
        }

        // verify the required parameter 'instanceId' is set
        if ($instanceId === null || (is_array($instanceId) && count($instanceId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $instanceId when calling getStateEducationAgencyByIdAsync'
            );
        }

        // verify the required parameter 'year' is set
        if ($year === null || (is_array($year) && count($year) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $year when calling getStateEducationAgencyByIdAsync'
            );
        }

        // verify the required parameter 'stateEducationAgencyId' is set
        if ($stateEducationAgencyId === null || (is_array($stateEducationAgencyId) && count($stateEducationAgencyId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $stateEducationAgencyId when calling getStateEducationAgencyByIdAsync'
            );
        }


        $resourcePath = '/tenants/{tenantId}/edfiadmin/instances/{instanceId}/years/{year}/stateeducationagencies/{stateEducationAgencyId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($tenantId !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenantId),
                $resourcePath
            );
        }
        // path params
        if ($instanceId !== null) {
            $resourcePath = str_replace(
                '{' . 'instanceId' . '}',
                ObjectSerializer::toPathValue($instanceId),
                $resourcePath
            );
        }
        // path params
        if ($year !== null) {
            $resourcePath = str_replace(
                '{' . 'year' . '}',
                ObjectSerializer::toPathValue($year),
                $resourcePath
            );
        }
        // path params
        if ($stateEducationAgencyId !== null) {
            $resourcePath = str_replace(
                '{' . 'stateEducationAgencyId' . '}',
                ObjectSerializer::toPathValue($stateEducationAgencyId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateStateEducationAgencyAsync
     *
     * Updates a StateEducationAgency.
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  string $stateEducationAgencyId  (required)
     * @param  \EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest $edfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateStateEducationAgencyAsync'] to see the possible values for this operation
     *
     * @throws \EdGraph\PlatformClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function updateStateEducationAgencyAsync($tenantId, $instanceId, $year, $stateEducationAgencyId, $edfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest = null, string $contentType = self::contentTypes['updateStateEducationAgencyAsync'][0])
    {
        $this->updateStateEducationAgencyAsyncWithHttpInfo($tenantId, $instanceId, $year, $stateEducationAgencyId, $edfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest, $contentType);
    }

    /**
     * Operation updateStateEducationAgencyAsyncWithHttpInfo
     *
     * Updates a StateEducationAgency.
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  string $stateEducationAgencyId  (required)
     * @param  \EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest $edfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateStateEducationAgencyAsync'] to see the possible values for this operation
     *
     * @throws \EdGraph\PlatformClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateStateEducationAgencyAsyncWithHttpInfo($tenantId, $instanceId, $year, $stateEducationAgencyId, $edfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest = null, string $contentType = self::contentTypes['updateStateEducationAgencyAsync'][0])
    {
        $request = $this->updateStateEducationAgencyAsyncRequest($tenantId, $instanceId, $year, $stateEducationAgencyId, $edfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateStateEducationAgencyAsyncAsync
     *
     * Updates a StateEducationAgency.
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  string $stateEducationAgencyId  (required)
     * @param  \EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest $edfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateStateEducationAgencyAsync'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateStateEducationAgencyAsyncAsync($tenantId, $instanceId, $year, $stateEducationAgencyId, $edfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest = null, string $contentType = self::contentTypes['updateStateEducationAgencyAsync'][0])
    {
        return $this->updateStateEducationAgencyAsyncAsyncWithHttpInfo($tenantId, $instanceId, $year, $stateEducationAgencyId, $edfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateStateEducationAgencyAsyncAsyncWithHttpInfo
     *
     * Updates a StateEducationAgency.
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  string $stateEducationAgencyId  (required)
     * @param  \EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest $edfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateStateEducationAgencyAsync'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateStateEducationAgencyAsyncAsyncWithHttpInfo($tenantId, $instanceId, $year, $stateEducationAgencyId, $edfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest = null, string $contentType = self::contentTypes['updateStateEducationAgencyAsync'][0])
    {
        $returnType = '';
        $request = $this->updateStateEducationAgencyAsyncRequest($tenantId, $instanceId, $year, $stateEducationAgencyId, $edfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateStateEducationAgencyAsync'
     *
     * @param  string $tenantId  (required)
     * @param  string $instanceId  (required)
     * @param  int $year  (required)
     * @param  string $stateEducationAgencyId  (required)
     * @param  \EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest $edfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateStateEducationAgencyAsync'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateStateEducationAgencyAsyncRequest($tenantId, $instanceId, $year, $stateEducationAgencyId, $edfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest = null, string $contentType = self::contentTypes['updateStateEducationAgencyAsync'][0])
    {

        // verify the required parameter 'tenantId' is set
        if ($tenantId === null || (is_array($tenantId) && count($tenantId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenantId when calling updateStateEducationAgencyAsync'
            );
        }

        // verify the required parameter 'instanceId' is set
        if ($instanceId === null || (is_array($instanceId) && count($instanceId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $instanceId when calling updateStateEducationAgencyAsync'
            );
        }

        // verify the required parameter 'year' is set
        if ($year === null || (is_array($year) && count($year) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $year when calling updateStateEducationAgencyAsync'
            );
        }

        // verify the required parameter 'stateEducationAgencyId' is set
        if ($stateEducationAgencyId === null || (is_array($stateEducationAgencyId) && count($stateEducationAgencyId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $stateEducationAgencyId when calling updateStateEducationAgencyAsync'
            );
        }



        $resourcePath = '/tenants/{tenantId}/edfiadmin/instances/{instanceId}/years/{year}/stateeducationagencies/{stateEducationAgencyId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($tenantId !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenantId),
                $resourcePath
            );
        }
        // path params
        if ($instanceId !== null) {
            $resourcePath = str_replace(
                '{' . 'instanceId' . '}',
                ObjectSerializer::toPathValue($instanceId),
                $resourcePath
            );
        }
        // path params
        if ($year !== null) {
            $resourcePath = str_replace(
                '{' . 'year' . '}',
                ObjectSerializer::toPathValue($year),
                $resourcePath
            );
        }
        // path params
        if ($stateEducationAgencyId !== null) {
            $resourcePath = str_replace(
                '{' . 'stateEducationAgencyId' . '}',
                ObjectSerializer::toPathValue($stateEducationAgencyId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($edfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($edfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest));
            } else {
                $httpBody = $edfiAdminApiEdfiAdminV1UpdateStateEducationAgencyRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
