<?php
/**
 * UsersSEOAAsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EdGraph\PlatformClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use EdGraph\PlatformClient\ApiException;
use EdGraph\PlatformClient\Configuration;
use EdGraph\PlatformClient\HeaderSelector;
use EdGraph\PlatformClient\ObjectSerializer;

/**
 * UsersSEOAAsApi Class Doc Comment
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UsersSEOAAsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'addUserSEOAA' => [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'deleteUserSEOAA' => [
            'application/json',
        ],
        'searchUserSEOAA' => [
            'application/json',
        ],
        'updateUserSEOAA' => [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/*+json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation addUserSEOAA
     *
     * Add User SEOAAs
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  \EdGraph\PlatformClient\Model\EdGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest $edGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addUserSEOAA'] to see the possible values for this operation
     *
     * @throws \EdGraph\PlatformClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAAddedResponse|\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails
     */
    public function addUserSEOAA($tenantId, $userId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest = null, string $contentType = self::contentTypes['addUserSEOAA'][0])
    {
        list($response) = $this->addUserSEOAAWithHttpInfo($tenantId, $userId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest, $contentType);
        return $response;
    }

    /**
     * Operation addUserSEOAAWithHttpInfo
     *
     * Add User SEOAAs
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  \EdGraph\PlatformClient\Model\EdGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest $edGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addUserSEOAA'] to see the possible values for this operation
     *
     * @throws \EdGraph\PlatformClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAAddedResponse|\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function addUserSEOAAWithHttpInfo($tenantId, $userId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest = null, string $contentType = self::contentTypes['addUserSEOAA'][0])
    {
        $request = $this->addUserSEOAARequest($tenantId, $userId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 401:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 200:
                    if ('\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAAddedResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAAddedResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAAddedResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAAddedResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAAddedResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation addUserSEOAAAsync
     *
     * Add User SEOAAs
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  \EdGraph\PlatformClient\Model\EdGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest $edGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addUserSEOAA'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addUserSEOAAAsync($tenantId, $userId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest = null, string $contentType = self::contentTypes['addUserSEOAA'][0])
    {
        return $this->addUserSEOAAAsyncWithHttpInfo($tenantId, $userId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation addUserSEOAAAsyncWithHttpInfo
     *
     * Add User SEOAAs
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  \EdGraph\PlatformClient\Model\EdGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest $edGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addUserSEOAA'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addUserSEOAAAsyncWithHttpInfo($tenantId, $userId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest = null, string $contentType = self::contentTypes['addUserSEOAA'][0])
    {
        $returnType = '\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAAddedResponse';
        $request = $this->addUserSEOAARequest($tenantId, $userId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'addUserSEOAA'
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  \EdGraph\PlatformClient\Model\EdGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest $edGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['addUserSEOAA'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function addUserSEOAARequest($tenantId, $userId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest = null, string $contentType = self::contentTypes['addUserSEOAA'][0])
    {

        // verify the required parameter 'tenantId' is set
        if ($tenantId === null || (is_array($tenantId) && count($tenantId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenantId when calling addUserSEOAA'
            );
        }

        // verify the required parameter 'userId' is set
        if ($userId === null || (is_array($userId) && count($userId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $userId when calling addUserSEOAA'
            );
        }



        $resourcePath = '/v2/tenants/{tenantId}/users/{userId}/seoaas';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($tenantId !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenantId),
                $resourcePath
            );
        }
        // path params
        if ($userId !== null) {
            $resourcePath = str_replace(
                '{' . 'userId' . '}',
                ObjectSerializer::toPathValue($userId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($edGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($edGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest));
            } else {
                $httpBody = $edGraphHttpAggregatorsTenantApiControllersV2RequestsAddSeoaaRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteUserSEOAA
     *
     * Delete User SEOAAs
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  string $seoaaId  (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteUserSEOAA'] to see the possible values for this operation
     *
     * @throws \EdGraph\PlatformClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAUpdatedResponse|\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails
     */
    public function deleteUserSEOAA($tenantId, $userId, $seoaaId, string $contentType = self::contentTypes['deleteUserSEOAA'][0])
    {
        list($response) = $this->deleteUserSEOAAWithHttpInfo($tenantId, $userId, $seoaaId, $contentType);
        return $response;
    }

    /**
     * Operation deleteUserSEOAAWithHttpInfo
     *
     * Delete User SEOAAs
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  string $seoaaId  (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteUserSEOAA'] to see the possible values for this operation
     *
     * @throws \EdGraph\PlatformClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAUpdatedResponse|\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteUserSEOAAWithHttpInfo($tenantId, $userId, $seoaaId, string $contentType = self::contentTypes['deleteUserSEOAA'][0])
    {
        $request = $this->deleteUserSEOAARequest($tenantId, $userId, $seoaaId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 401:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 200:
                    if ('\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAUpdatedResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAUpdatedResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAUpdatedResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAUpdatedResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAUpdatedResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteUserSEOAAAsync
     *
     * Delete User SEOAAs
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  string $seoaaId  (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteUserSEOAA'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteUserSEOAAAsync($tenantId, $userId, $seoaaId, string $contentType = self::contentTypes['deleteUserSEOAA'][0])
    {
        return $this->deleteUserSEOAAAsyncWithHttpInfo($tenantId, $userId, $seoaaId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteUserSEOAAAsyncWithHttpInfo
     *
     * Delete User SEOAAs
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  string $seoaaId  (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteUserSEOAA'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteUserSEOAAAsyncWithHttpInfo($tenantId, $userId, $seoaaId, string $contentType = self::contentTypes['deleteUserSEOAA'][0])
    {
        $returnType = '\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAUpdatedResponse';
        $request = $this->deleteUserSEOAARequest($tenantId, $userId, $seoaaId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteUserSEOAA'
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  string $seoaaId  (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteUserSEOAA'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteUserSEOAARequest($tenantId, $userId, $seoaaId, string $contentType = self::contentTypes['deleteUserSEOAA'][0])
    {

        // verify the required parameter 'tenantId' is set
        if ($tenantId === null || (is_array($tenantId) && count($tenantId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenantId when calling deleteUserSEOAA'
            );
        }

        // verify the required parameter 'userId' is set
        if ($userId === null || (is_array($userId) && count($userId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $userId when calling deleteUserSEOAA'
            );
        }

        // verify the required parameter 'seoaaId' is set
        if ($seoaaId === null || (is_array($seoaaId) && count($seoaaId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $seoaaId when calling deleteUserSEOAA'
            );
        }


        $resourcePath = '/v2/tenants/{tenantId}/users/{userId}/seoaas/{seoaaId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($tenantId !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenantId),
                $resourcePath
            );
        }
        // path params
        if ($userId !== null) {
            $resourcePath = str_replace(
                '{' . 'userId' . '}',
                ObjectSerializer::toPathValue($userId),
                $resourcePath
            );
        }
        // path params
        if ($seoaaId !== null) {
            $resourcePath = str_replace(
                '{' . 'seoaaId' . '}',
                ObjectSerializer::toPathValue($seoaaId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchUserSEOAA
     *
     * Search User SEOAAs
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  int $pageSize  (optional, default to 10)
     * @param  int $pageIndex  (optional, default to 0)
     * @param  string $orderBy  (optional, default to '')
     * @param  string $filter  (optional, default to '')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchUserSEOAA'] to see the possible values for this operation
     *
     * @throws \EdGraph\PlatformClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\IdentityApiUserV1GetSEOAAsResponse|\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails
     */
    public function searchUserSEOAA($tenantId, $userId, $pageSize = 10, $pageIndex = 0, $orderBy = '', $filter = '', string $contentType = self::contentTypes['searchUserSEOAA'][0])
    {
        list($response) = $this->searchUserSEOAAWithHttpInfo($tenantId, $userId, $pageSize, $pageIndex, $orderBy, $filter, $contentType);
        return $response;
    }

    /**
     * Operation searchUserSEOAAWithHttpInfo
     *
     * Search User SEOAAs
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  int $pageSize  (optional, default to 10)
     * @param  int $pageIndex  (optional, default to 0)
     * @param  string $orderBy  (optional, default to '')
     * @param  string $filter  (optional, default to '')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchUserSEOAA'] to see the possible values for this operation
     *
     * @throws \EdGraph\PlatformClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\IdentityApiUserV1GetSEOAAsResponse|\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchUserSEOAAWithHttpInfo($tenantId, $userId, $pageSize = 10, $pageIndex = 0, $orderBy = '', $filter = '', string $contentType = self::contentTypes['searchUserSEOAA'][0])
    {
        $request = $this->searchUserSEOAARequest($tenantId, $userId, $pageSize, $pageIndex, $orderBy, $filter, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 401:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 200:
                    if ('\EdGraph\PlatformClient\Model\IdentityApiUserV1GetSEOAAsResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\IdentityApiUserV1GetSEOAAsResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\IdentityApiUserV1GetSEOAAsResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\EdGraph\PlatformClient\Model\IdentityApiUserV1GetSEOAAsResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\IdentityApiUserV1GetSEOAAsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation searchUserSEOAAAsync
     *
     * Search User SEOAAs
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  int $pageSize  (optional, default to 10)
     * @param  int $pageIndex  (optional, default to 0)
     * @param  string $orderBy  (optional, default to '')
     * @param  string $filter  (optional, default to '')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchUserSEOAA'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchUserSEOAAAsync($tenantId, $userId, $pageSize = 10, $pageIndex = 0, $orderBy = '', $filter = '', string $contentType = self::contentTypes['searchUserSEOAA'][0])
    {
        return $this->searchUserSEOAAAsyncWithHttpInfo($tenantId, $userId, $pageSize, $pageIndex, $orderBy, $filter, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchUserSEOAAAsyncWithHttpInfo
     *
     * Search User SEOAAs
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  int $pageSize  (optional, default to 10)
     * @param  int $pageIndex  (optional, default to 0)
     * @param  string $orderBy  (optional, default to '')
     * @param  string $filter  (optional, default to '')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchUserSEOAA'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchUserSEOAAAsyncWithHttpInfo($tenantId, $userId, $pageSize = 10, $pageIndex = 0, $orderBy = '', $filter = '', string $contentType = self::contentTypes['searchUserSEOAA'][0])
    {
        $returnType = '\EdGraph\PlatformClient\Model\IdentityApiUserV1GetSEOAAsResponse';
        $request = $this->searchUserSEOAARequest($tenantId, $userId, $pageSize, $pageIndex, $orderBy, $filter, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchUserSEOAA'
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  int $pageSize  (optional, default to 10)
     * @param  int $pageIndex  (optional, default to 0)
     * @param  string $orderBy  (optional, default to '')
     * @param  string $filter  (optional, default to '')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchUserSEOAA'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchUserSEOAARequest($tenantId, $userId, $pageSize = 10, $pageIndex = 0, $orderBy = '', $filter = '', string $contentType = self::contentTypes['searchUserSEOAA'][0])
    {

        // verify the required parameter 'tenantId' is set
        if ($tenantId === null || (is_array($tenantId) && count($tenantId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenantId when calling searchUserSEOAA'
            );
        }

        // verify the required parameter 'userId' is set
        if ($userId === null || (is_array($userId) && count($userId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $userId when calling searchUserSEOAA'
            );
        }






        $resourcePath = '/v2/tenants/{tenantId}/users/{userId}/seoaas';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $pageSize,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $pageIndex,
            'pageIndex', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $orderBy,
            'orderBy', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter,
            'filter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($tenantId !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenantId),
                $resourcePath
            );
        }
        // path params
        if ($userId !== null) {
            $resourcePath = str_replace(
                '{' . 'userId' . '}',
                ObjectSerializer::toPathValue($userId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateUserSEOAA
     *
     * Update User SEOAAs
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  string $seoaaId  (required)
     * @param  \EdGraph\PlatformClient\Model\EdGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest $edGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateUserSEOAA'] to see the possible values for this operation
     *
     * @throws \EdGraph\PlatformClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAUpdatedResponse|\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails
     */
    public function updateUserSEOAA($tenantId, $userId, $seoaaId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest = null, string $contentType = self::contentTypes['updateUserSEOAA'][0])
    {
        list($response) = $this->updateUserSEOAAWithHttpInfo($tenantId, $userId, $seoaaId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest, $contentType);
        return $response;
    }

    /**
     * Operation updateUserSEOAAWithHttpInfo
     *
     * Update User SEOAAs
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  string $seoaaId  (required)
     * @param  \EdGraph\PlatformClient\Model\EdGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest $edGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateUserSEOAA'] to see the possible values for this operation
     *
     * @throws \EdGraph\PlatformClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails|\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAUpdatedResponse|\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateUserSEOAAWithHttpInfo($tenantId, $userId, $seoaaId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest = null, string $contentType = self::contentTypes['updateUserSEOAA'][0])
    {
        $request = $this->updateUserSEOAARequest($tenantId, $userId, $seoaaId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 401:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 200:
                    if ('\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAUpdatedResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAUpdatedResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAUpdatedResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAUpdatedResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\EdGraphCommonErrorsCoreProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAUpdatedResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EdGraph\PlatformClient\Model\MicrosoftAspNetCoreMvcValidationProblemDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateUserSEOAAAsync
     *
     * Update User SEOAAs
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  string $seoaaId  (required)
     * @param  \EdGraph\PlatformClient\Model\EdGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest $edGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateUserSEOAA'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateUserSEOAAAsync($tenantId, $userId, $seoaaId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest = null, string $contentType = self::contentTypes['updateUserSEOAA'][0])
    {
        return $this->updateUserSEOAAAsyncWithHttpInfo($tenantId, $userId, $seoaaId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateUserSEOAAAsyncWithHttpInfo
     *
     * Update User SEOAAs
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  string $seoaaId  (required)
     * @param  \EdGraph\PlatformClient\Model\EdGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest $edGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateUserSEOAA'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateUserSEOAAAsyncWithHttpInfo($tenantId, $userId, $seoaaId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest = null, string $contentType = self::contentTypes['updateUserSEOAA'][0])
    {
        $returnType = '\EdGraph\PlatformClient\Model\IdentityApiUserV1SEOAAUpdatedResponse';
        $request = $this->updateUserSEOAARequest($tenantId, $userId, $seoaaId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateUserSEOAA'
     *
     * @param  string $tenantId  (required)
     * @param  string $userId  (required)
     * @param  string $seoaaId  (required)
     * @param  \EdGraph\PlatformClient\Model\EdGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest $edGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest  (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateUserSEOAA'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateUserSEOAARequest($tenantId, $userId, $seoaaId, $edGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest = null, string $contentType = self::contentTypes['updateUserSEOAA'][0])
    {

        // verify the required parameter 'tenantId' is set
        if ($tenantId === null || (is_array($tenantId) && count($tenantId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenantId when calling updateUserSEOAA'
            );
        }

        // verify the required parameter 'userId' is set
        if ($userId === null || (is_array($userId) && count($userId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $userId when calling updateUserSEOAA'
            );
        }

        // verify the required parameter 'seoaaId' is set
        if ($seoaaId === null || (is_array($seoaaId) && count($seoaaId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $seoaaId when calling updateUserSEOAA'
            );
        }



        $resourcePath = '/v2/tenants/{tenantId}/users/{userId}/seoaas/{seoaaId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($tenantId !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenantId),
                $resourcePath
            );
        }
        // path params
        if ($userId !== null) {
            $resourcePath = str_replace(
                '{' . 'userId' . '}',
                ObjectSerializer::toPathValue($userId),
                $resourcePath
            );
        }
        // path params
        if ($seoaaId !== null) {
            $resourcePath = str_replace(
                '{' . 'seoaaId' . '}',
                ObjectSerializer::toPathValue($seoaaId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($edGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($edGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest));
            } else {
                $httpBody = $edGraphHttpAggregatorsTenantApiControllersV2RequestsUpdateSeoaaRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
