<?php
/**
 * EdGraphServicesStateReportingV1ReportingPeriodCertificationStatusTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EdGraph\PlatformClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EdGraphServicesStateReportingV1ReportingPeriodCertificationStatusTest Class Doc Comment
 *
 * @category    Class
 * @description EdGraphServicesStateReportingV1ReportingPeriodCertificationStatus
 * @package     EdGraph\PlatformClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EdGraphServicesStateReportingV1ReportingPeriodCertificationStatusTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EdGraphServicesStateReportingV1ReportingPeriodCertificationStatus"
     */
    public function testEdGraphServicesStateReportingV1ReportingPeriodCertificationStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tenantId"
     */
    public function testPropertyTenantId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "environmentId"
     */
    public function testPropertyEnvironmentId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reportingPeriod"
     */
    public function testPropertyReportingPeriod()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "certificationPercentage"
     */
    public function testPropertyCertificationPercentage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
