<?php
/**
 * FormApiFormsV1SetFormAccessRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EdGraph\PlatformClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * FormApiFormsV1SetFormAccessRequestTest Class Doc Comment
 *
 * @category    Class
 * @description FormApiFormsV1SetFormAccessRequest
 * @package     EdGraph\PlatformClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FormApiFormsV1SetFormAccessRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "FormApiFormsV1SetFormAccessRequest"
     */
    public function testFormApiFormsV1SetFormAccessRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tenantId"
     */
    public function testPropertyTenantId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "targetAudience"
     */
    public function testPropertyTargetAudience()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "singleResponsePerIndividual"
     */
    public function testPropertySingleResponsePerIndividual()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "staffClassifications"
     */
    public function testPropertyStaffClassifications()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "users"
     */
    public function testPropertyUsers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
