<?php
/**
 * EdfiAdminApiEdfiAdminV1InstanceEndpointsResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EdGraph\PlatformClient\Model;

use \ArrayAccess;
use \EdGraph\PlatformClient\ObjectSerializer;

/**
 * EdfiAdminApiEdfiAdminV1InstanceEndpointsResponse Class Doc Comment
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EdfiAdminApiEdfiAdminV1InstanceEndpointsResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'EdfiAdminApi.EdfiAdmin.V1.InstanceEndpointsResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'authUrl' => 'string',
        'resourcesUrls' => '\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1ApplicationEndpoint[]',
        'compositesUrls' => '\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1ApplicationEndpoint[]',
        'discoveryUrls' => '\EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1ApplicationEndpoint[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'authUrl' => null,
        'resourcesUrls' => null,
        'compositesUrls' => null,
        'discoveryUrls' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'authUrl' => true,
        'resourcesUrls' => true,
        'compositesUrls' => true,
        'discoveryUrls' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'authUrl' => 'authUrl',
        'resourcesUrls' => 'resourcesUrls',
        'compositesUrls' => 'compositesUrls',
        'discoveryUrls' => 'discoveryUrls'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'authUrl' => 'setAuthUrl',
        'resourcesUrls' => 'setResourcesUrls',
        'compositesUrls' => 'setCompositesUrls',
        'discoveryUrls' => 'setDiscoveryUrls'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'authUrl' => 'getAuthUrl',
        'resourcesUrls' => 'getResourcesUrls',
        'compositesUrls' => 'getCompositesUrls',
        'discoveryUrls' => 'getDiscoveryUrls'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('authUrl', $data ?? [], null);
        $this->setIfExists('resourcesUrls', $data ?? [], null);
        $this->setIfExists('compositesUrls', $data ?? [], null);
        $this->setIfExists('discoveryUrls', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets authUrl
     *
     * @return string|null
     */
    public function getAuthUrl()
    {
        return $this->container['authUrl'];
    }

    /**
     * Sets authUrl
     *
     * @param string|null $authUrl authUrl
     *
     * @return self
     */
    public function setAuthUrl($authUrl)
    {
        if (is_null($authUrl)) {
            array_push($this->openAPINullablesSetToNull, 'authUrl');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authUrl', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authUrl'] = $authUrl;

        return $this;
    }

    /**
     * Gets resourcesUrls
     *
     * @return \EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1ApplicationEndpoint[]|null
     */
    public function getResourcesUrls()
    {
        return $this->container['resourcesUrls'];
    }

    /**
     * Sets resourcesUrls
     *
     * @param \EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1ApplicationEndpoint[]|null $resourcesUrls resourcesUrls
     *
     * @return self
     */
    public function setResourcesUrls($resourcesUrls)
    {
        if (is_null($resourcesUrls)) {
            array_push($this->openAPINullablesSetToNull, 'resourcesUrls');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('resourcesUrls', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['resourcesUrls'] = $resourcesUrls;

        return $this;
    }

    /**
     * Gets compositesUrls
     *
     * @return \EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1ApplicationEndpoint[]|null
     */
    public function getCompositesUrls()
    {
        return $this->container['compositesUrls'];
    }

    /**
     * Sets compositesUrls
     *
     * @param \EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1ApplicationEndpoint[]|null $compositesUrls compositesUrls
     *
     * @return self
     */
    public function setCompositesUrls($compositesUrls)
    {
        if (is_null($compositesUrls)) {
            array_push($this->openAPINullablesSetToNull, 'compositesUrls');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('compositesUrls', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['compositesUrls'] = $compositesUrls;

        return $this;
    }

    /**
     * Gets discoveryUrls
     *
     * @return \EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1ApplicationEndpoint[]|null
     */
    public function getDiscoveryUrls()
    {
        return $this->container['discoveryUrls'];
    }

    /**
     * Sets discoveryUrls
     *
     * @param \EdGraph\PlatformClient\Model\EdfiAdminApiEdfiAdminV1ApplicationEndpoint[]|null $discoveryUrls discoveryUrls
     *
     * @return self
     */
    public function setDiscoveryUrls($discoveryUrls)
    {
        if (is_null($discoveryUrls)) {
            array_push($this->openAPINullablesSetToNull, 'discoveryUrls');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('discoveryUrls', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['discoveryUrls'] = $discoveryUrls;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


