<?php
/**
 * EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminProgramListItemDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EdGraph\PlatformClient\Model;

use \ArrayAccess;
use \EdGraph\PlatformClient\ObjectSerializer;

/**
 * EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminProgramListItemDto Class Doc Comment
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EdGraphHttpAggregatorsTenantApiControllersV1ViewModelsResponsesEnrollmentAdminProgramListItemDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'EdGraph.HttpAggregators.Tenant.Api.Controllers.v1.ViewModels.Responses.EnrollmentAdmin.ProgramListItemDto';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'code' => 'string',
        'name' => 'string',
        'scope' => 'string',
        'schoolCount' => 'int',
        'schoolName' => 'string',
        'programType' => 'string',
        'grades' => 'string[]',
        'gradesVaryBySchool' => 'bool',
        'seatStatus' => 'string',
        'seatStatusVariesBySchool' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'code' => null,
        'name' => null,
        'scope' => null,
        'schoolCount' => 'int32',
        'schoolName' => null,
        'programType' => null,
        'grades' => null,
        'gradesVaryBySchool' => null,
        'seatStatus' => null,
        'seatStatusVariesBySchool' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => true,
        'code' => true,
        'name' => true,
        'scope' => true,
        'schoolCount' => false,
        'schoolName' => true,
        'programType' => true,
        'grades' => true,
        'gradesVaryBySchool' => false,
        'seatStatus' => true,
        'seatStatusVariesBySchool' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'code' => 'code',
        'name' => 'name',
        'scope' => 'scope',
        'schoolCount' => 'schoolCount',
        'schoolName' => 'schoolName',
        'programType' => 'programType',
        'grades' => 'grades',
        'gradesVaryBySchool' => 'gradesVaryBySchool',
        'seatStatus' => 'seatStatus',
        'seatStatusVariesBySchool' => 'seatStatusVariesBySchool'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'code' => 'setCode',
        'name' => 'setName',
        'scope' => 'setScope',
        'schoolCount' => 'setSchoolCount',
        'schoolName' => 'setSchoolName',
        'programType' => 'setProgramType',
        'grades' => 'setGrades',
        'gradesVaryBySchool' => 'setGradesVaryBySchool',
        'seatStatus' => 'setSeatStatus',
        'seatStatusVariesBySchool' => 'setSeatStatusVariesBySchool'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'code' => 'getCode',
        'name' => 'getName',
        'scope' => 'getScope',
        'schoolCount' => 'getSchoolCount',
        'schoolName' => 'getSchoolName',
        'programType' => 'getProgramType',
        'grades' => 'getGrades',
        'gradesVaryBySchool' => 'getGradesVaryBySchool',
        'seatStatus' => 'getSeatStatus',
        'seatStatusVariesBySchool' => 'getSeatStatusVariesBySchool'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('scope', $data ?? [], null);
        $this->setIfExists('schoolCount', $data ?? [], null);
        $this->setIfExists('schoolName', $data ?? [], null);
        $this->setIfExists('programType', $data ?? [], null);
        $this->setIfExists('grades', $data ?? [], null);
        $this->setIfExists('gradesVaryBySchool', $data ?? [], null);
        $this->setIfExists('seatStatus', $data ?? [], null);
        $this->setIfExists('seatStatusVariesBySchool', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code code
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            array_push($this->openAPINullablesSetToNull, 'code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets scope
     *
     * @return string|null
     */
    public function getScope()
    {
        return $this->container['scope'];
    }

    /**
     * Sets scope
     *
     * @param string|null $scope scope
     *
     * @return self
     */
    public function setScope($scope)
    {
        if (is_null($scope)) {
            array_push($this->openAPINullablesSetToNull, 'scope');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('scope', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['scope'] = $scope;

        return $this;
    }

    /**
     * Gets schoolCount
     *
     * @return int|null
     */
    public function getSchoolCount()
    {
        return $this->container['schoolCount'];
    }

    /**
     * Sets schoolCount
     *
     * @param int|null $schoolCount schoolCount
     *
     * @return self
     */
    public function setSchoolCount($schoolCount)
    {
        if (is_null($schoolCount)) {
            throw new \InvalidArgumentException('non-nullable schoolCount cannot be null');
        }
        $this->container['schoolCount'] = $schoolCount;

        return $this;
    }

    /**
     * Gets schoolName
     *
     * @return string|null
     */
    public function getSchoolName()
    {
        return $this->container['schoolName'];
    }

    /**
     * Sets schoolName
     *
     * @param string|null $schoolName schoolName
     *
     * @return self
     */
    public function setSchoolName($schoolName)
    {
        if (is_null($schoolName)) {
            array_push($this->openAPINullablesSetToNull, 'schoolName');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('schoolName', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['schoolName'] = $schoolName;

        return $this;
    }

    /**
     * Gets programType
     *
     * @return string|null
     */
    public function getProgramType()
    {
        return $this->container['programType'];
    }

    /**
     * Sets programType
     *
     * @param string|null $programType programType
     *
     * @return self
     */
    public function setProgramType($programType)
    {
        if (is_null($programType)) {
            array_push($this->openAPINullablesSetToNull, 'programType');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('programType', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['programType'] = $programType;

        return $this;
    }

    /**
     * Gets grades
     *
     * @return string[]|null
     */
    public function getGrades()
    {
        return $this->container['grades'];
    }

    /**
     * Sets grades
     *
     * @param string[]|null $grades grades
     *
     * @return self
     */
    public function setGrades($grades)
    {
        if (is_null($grades)) {
            array_push($this->openAPINullablesSetToNull, 'grades');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('grades', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['grades'] = $grades;

        return $this;
    }

    /**
     * Gets gradesVaryBySchool
     *
     * @return bool|null
     */
    public function getGradesVaryBySchool()
    {
        return $this->container['gradesVaryBySchool'];
    }

    /**
     * Sets gradesVaryBySchool
     *
     * @param bool|null $gradesVaryBySchool gradesVaryBySchool
     *
     * @return self
     */
    public function setGradesVaryBySchool($gradesVaryBySchool)
    {
        if (is_null($gradesVaryBySchool)) {
            throw new \InvalidArgumentException('non-nullable gradesVaryBySchool cannot be null');
        }
        $this->container['gradesVaryBySchool'] = $gradesVaryBySchool;

        return $this;
    }

    /**
     * Gets seatStatus
     *
     * @return string|null
     */
    public function getSeatStatus()
    {
        return $this->container['seatStatus'];
    }

    /**
     * Sets seatStatus
     *
     * @param string|null $seatStatus seatStatus
     *
     * @return self
     */
    public function setSeatStatus($seatStatus)
    {
        if (is_null($seatStatus)) {
            array_push($this->openAPINullablesSetToNull, 'seatStatus');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('seatStatus', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['seatStatus'] = $seatStatus;

        return $this;
    }

    /**
     * Gets seatStatusVariesBySchool
     *
     * @return bool|null
     */
    public function getSeatStatusVariesBySchool()
    {
        return $this->container['seatStatusVariesBySchool'];
    }

    /**
     * Sets seatStatusVariesBySchool
     *
     * @param bool|null $seatStatusVariesBySchool seatStatusVariesBySchool
     *
     * @return self
     */
    public function setSeatStatusVariesBySchool($seatStatusVariesBySchool)
    {
        if (is_null($seatStatusVariesBySchool)) {
            throw new \InvalidArgumentException('non-nullable seatStatusVariesBySchool cannot be null');
        }
        $this->container['seatStatusVariesBySchool'] = $seatStatusVariesBySchool;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


