<?php
/**
 * GoogleProtobufWellKnownTypesValue
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EdGraph\PlatformClient\Model;

use \ArrayAccess;
use \EdGraph\PlatformClient\ObjectSerializer;

/**
 * GoogleProtobufWellKnownTypesValue Class Doc Comment
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GoogleProtobufWellKnownTypesValue implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Google.Protobuf.WellKnownTypes.Value';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'nullValue' => '\EdGraph\PlatformClient\Model\GoogleProtobufWellKnownTypesNullValue',
        'hasNullValue' => 'bool',
        'numberValue' => 'float',
        'hasNumberValue' => 'bool',
        'stringValue' => 'string',
        'hasStringValue' => 'bool',
        'boolValue' => 'bool',
        'hasBoolValue' => 'bool',
        'structValue' => '\EdGraph\PlatformClient\Model\GoogleProtobufWellKnownTypesStruct',
        'listValue' => '\EdGraph\PlatformClient\Model\GoogleProtobufWellKnownTypesListValue',
        'kindCase' => '\EdGraph\PlatformClient\Model\GoogleProtobufWellKnownTypesValueKindOneofCase'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'nullValue' => null,
        'hasNullValue' => null,
        'numberValue' => 'double',
        'hasNumberValue' => null,
        'stringValue' => null,
        'hasStringValue' => null,
        'boolValue' => null,
        'hasBoolValue' => null,
        'structValue' => null,
        'listValue' => null,
        'kindCase' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'nullValue' => false,
        'hasNullValue' => false,
        'numberValue' => false,
        'hasNumberValue' => false,
        'stringValue' => true,
        'hasStringValue' => false,
        'boolValue' => false,
        'hasBoolValue' => false,
        'structValue' => false,
        'listValue' => false,
        'kindCase' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'nullValue' => 'nullValue',
        'hasNullValue' => 'hasNullValue',
        'numberValue' => 'numberValue',
        'hasNumberValue' => 'hasNumberValue',
        'stringValue' => 'stringValue',
        'hasStringValue' => 'hasStringValue',
        'boolValue' => 'boolValue',
        'hasBoolValue' => 'hasBoolValue',
        'structValue' => 'structValue',
        'listValue' => 'listValue',
        'kindCase' => 'kindCase'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'nullValue' => 'setNullValue',
        'hasNullValue' => 'setHasNullValue',
        'numberValue' => 'setNumberValue',
        'hasNumberValue' => 'setHasNumberValue',
        'stringValue' => 'setStringValue',
        'hasStringValue' => 'setHasStringValue',
        'boolValue' => 'setBoolValue',
        'hasBoolValue' => 'setHasBoolValue',
        'structValue' => 'setStructValue',
        'listValue' => 'setListValue',
        'kindCase' => 'setKindCase'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'nullValue' => 'getNullValue',
        'hasNullValue' => 'getHasNullValue',
        'numberValue' => 'getNumberValue',
        'hasNumberValue' => 'getHasNumberValue',
        'stringValue' => 'getStringValue',
        'hasStringValue' => 'getHasStringValue',
        'boolValue' => 'getBoolValue',
        'hasBoolValue' => 'getHasBoolValue',
        'structValue' => 'getStructValue',
        'listValue' => 'getListValue',
        'kindCase' => 'getKindCase'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('nullValue', $data ?? [], null);
        $this->setIfExists('hasNullValue', $data ?? [], null);
        $this->setIfExists('numberValue', $data ?? [], null);
        $this->setIfExists('hasNumberValue', $data ?? [], null);
        $this->setIfExists('stringValue', $data ?? [], null);
        $this->setIfExists('hasStringValue', $data ?? [], null);
        $this->setIfExists('boolValue', $data ?? [], null);
        $this->setIfExists('hasBoolValue', $data ?? [], null);
        $this->setIfExists('structValue', $data ?? [], null);
        $this->setIfExists('listValue', $data ?? [], null);
        $this->setIfExists('kindCase', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets nullValue
     *
     * @return \EdGraph\PlatformClient\Model\GoogleProtobufWellKnownTypesNullValue|null
     */
    public function getNullValue()
    {
        return $this->container['nullValue'];
    }

    /**
     * Sets nullValue
     *
     * @param \EdGraph\PlatformClient\Model\GoogleProtobufWellKnownTypesNullValue|null $nullValue nullValue
     *
     * @return self
     */
    public function setNullValue($nullValue)
    {
        if (is_null($nullValue)) {
            throw new \InvalidArgumentException('non-nullable nullValue cannot be null');
        }
        $this->container['nullValue'] = $nullValue;

        return $this;
    }

    /**
     * Gets hasNullValue
     *
     * @return bool|null
     */
    public function getHasNullValue()
    {
        return $this->container['hasNullValue'];
    }

    /**
     * Sets hasNullValue
     *
     * @param bool|null $hasNullValue hasNullValue
     *
     * @return self
     */
    public function setHasNullValue($hasNullValue)
    {
        if (is_null($hasNullValue)) {
            throw new \InvalidArgumentException('non-nullable hasNullValue cannot be null');
        }
        $this->container['hasNullValue'] = $hasNullValue;

        return $this;
    }

    /**
     * Gets numberValue
     *
     * @return float|null
     */
    public function getNumberValue()
    {
        return $this->container['numberValue'];
    }

    /**
     * Sets numberValue
     *
     * @param float|null $numberValue numberValue
     *
     * @return self
     */
    public function setNumberValue($numberValue)
    {
        if (is_null($numberValue)) {
            throw new \InvalidArgumentException('non-nullable numberValue cannot be null');
        }
        $this->container['numberValue'] = $numberValue;

        return $this;
    }

    /**
     * Gets hasNumberValue
     *
     * @return bool|null
     */
    public function getHasNumberValue()
    {
        return $this->container['hasNumberValue'];
    }

    /**
     * Sets hasNumberValue
     *
     * @param bool|null $hasNumberValue hasNumberValue
     *
     * @return self
     */
    public function setHasNumberValue($hasNumberValue)
    {
        if (is_null($hasNumberValue)) {
            throw new \InvalidArgumentException('non-nullable hasNumberValue cannot be null');
        }
        $this->container['hasNumberValue'] = $hasNumberValue;

        return $this;
    }

    /**
     * Gets stringValue
     *
     * @return string|null
     */
    public function getStringValue()
    {
        return $this->container['stringValue'];
    }

    /**
     * Sets stringValue
     *
     * @param string|null $stringValue stringValue
     *
     * @return self
     */
    public function setStringValue($stringValue)
    {
        if (is_null($stringValue)) {
            array_push($this->openAPINullablesSetToNull, 'stringValue');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('stringValue', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['stringValue'] = $stringValue;

        return $this;
    }

    /**
     * Gets hasStringValue
     *
     * @return bool|null
     */
    public function getHasStringValue()
    {
        return $this->container['hasStringValue'];
    }

    /**
     * Sets hasStringValue
     *
     * @param bool|null $hasStringValue hasStringValue
     *
     * @return self
     */
    public function setHasStringValue($hasStringValue)
    {
        if (is_null($hasStringValue)) {
            throw new \InvalidArgumentException('non-nullable hasStringValue cannot be null');
        }
        $this->container['hasStringValue'] = $hasStringValue;

        return $this;
    }

    /**
     * Gets boolValue
     *
     * @return bool|null
     */
    public function getBoolValue()
    {
        return $this->container['boolValue'];
    }

    /**
     * Sets boolValue
     *
     * @param bool|null $boolValue boolValue
     *
     * @return self
     */
    public function setBoolValue($boolValue)
    {
        if (is_null($boolValue)) {
            throw new \InvalidArgumentException('non-nullable boolValue cannot be null');
        }
        $this->container['boolValue'] = $boolValue;

        return $this;
    }

    /**
     * Gets hasBoolValue
     *
     * @return bool|null
     */
    public function getHasBoolValue()
    {
        return $this->container['hasBoolValue'];
    }

    /**
     * Sets hasBoolValue
     *
     * @param bool|null $hasBoolValue hasBoolValue
     *
     * @return self
     */
    public function setHasBoolValue($hasBoolValue)
    {
        if (is_null($hasBoolValue)) {
            throw new \InvalidArgumentException('non-nullable hasBoolValue cannot be null');
        }
        $this->container['hasBoolValue'] = $hasBoolValue;

        return $this;
    }

    /**
     * Gets structValue
     *
     * @return \EdGraph\PlatformClient\Model\GoogleProtobufWellKnownTypesStruct|null
     */
    public function getStructValue()
    {
        return $this->container['structValue'];
    }

    /**
     * Sets structValue
     *
     * @param \EdGraph\PlatformClient\Model\GoogleProtobufWellKnownTypesStruct|null $structValue structValue
     *
     * @return self
     */
    public function setStructValue($structValue)
    {
        if (is_null($structValue)) {
            throw new \InvalidArgumentException('non-nullable structValue cannot be null');
        }
        $this->container['structValue'] = $structValue;

        return $this;
    }

    /**
     * Gets listValue
     *
     * @return \EdGraph\PlatformClient\Model\GoogleProtobufWellKnownTypesListValue|null
     */
    public function getListValue()
    {
        return $this->container['listValue'];
    }

    /**
     * Sets listValue
     *
     * @param \EdGraph\PlatformClient\Model\GoogleProtobufWellKnownTypesListValue|null $listValue listValue
     *
     * @return self
     */
    public function setListValue($listValue)
    {
        if (is_null($listValue)) {
            throw new \InvalidArgumentException('non-nullable listValue cannot be null');
        }
        $this->container['listValue'] = $listValue;

        return $this;
    }

    /**
     * Gets kindCase
     *
     * @return \EdGraph\PlatformClient\Model\GoogleProtobufWellKnownTypesValueKindOneofCase|null
     */
    public function getKindCase()
    {
        return $this->container['kindCase'];
    }

    /**
     * Sets kindCase
     *
     * @param \EdGraph\PlatformClient\Model\GoogleProtobufWellKnownTypesValueKindOneofCase|null $kindCase kindCase
     *
     * @return self
     */
    public function setKindCase($kindCase)
    {
        if (is_null($kindCase)) {
            throw new \InvalidArgumentException('non-nullable kindCase cannot be null');
        }
        $this->container['kindCase'] = $kindCase;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


