<?php
/**
 * IdentityApiUserV1RevokeStrategy
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EdGraph\PlatformClient\Model;
use \EdGraph\PlatformClient\ObjectSerializer;

/**
 * IdentityApiUserV1RevokeStrategy Class Doc Comment
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IdentityApiUserV1RevokeStrategy
{
    /**
     * Possible values of this enum
     */
    public const UNKNOWN = 'Unknown';

    public const REVOKE_IMPLICIT = 'RevokeImplicit';

    public const REVOKE_EXPLICIT = 'RevokeExplicit';

    public const UNDO_EXPLICIT_REVOKE = 'UndoExplicitRevoke';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::REVOKE_IMPLICIT,
            self::REVOKE_EXPLICIT,
            self::UNDO_EXPLICIT_REVOKE
        ];
    }
}


