<?php
/**
 * TenantApiTenantV1TenantProfileResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EdGraph\PlatformClient\Model;

use \ArrayAccess;
use \EdGraph\PlatformClient\ObjectSerializer;

/**
 * TenantApiTenantV1TenantProfileResponse Class Doc Comment
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TenantApiTenantV1TenantProfileResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TenantApi.Tenant.V1.TenantProfileResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'tenantId' => 'string',
        'tenantTypes' => '\EdGraph\PlatformClient\Model\TenantApiTenantV1TenantType[]',
        'organizationIdentifier' => 'string',
        'organizationName' => 'string',
        'state' => 'string',
        'tenantStatus' => '\EdGraph\PlatformClient\Model\TenantApiTenantV1TenantStatus',
        'isDemo' => 'bool',
        'subscriptionsMigrated' => 'bool',
        'subscriptions' => '\EdGraph\PlatformClient\Model\TenantApiTenantV1SubscriptionProfileResponse[]',
        'domains' => '\EdGraph\PlatformClient\Model\TenantApiTenantV1DomainProfileResponse[]',
        'createdBy' => 'string',
        'createdDateTime' => 'string',
        'lastModifiedBy' => 'string',
        'lastModifiedDateTime' => 'string',
        'identityProviders' => '\EdGraph\PlatformClient\Model\TenantApiTenantV1TenantIdentityProviders[]',
        'onboarding' => '\EdGraph\PlatformClient\Model\TenantApiTenantV1Onboarding',
        'organizations' => '\EdGraph\PlatformClient\Model\TenantApiTenantV1Organization[]',
        'organizationIdentifierHash' => 'string',
        'settings' => '\EdGraph\PlatformClient\Model\TenantApiTenantV1TenantSetting[]',
        'additionalSettings' => '\EdGraph\PlatformClient\Model\TenantApiTenantV1TenantAdditionalSetting',
        'tenantType' => 'string',
        'securityScore' => 'float',
        'organizationalAccountRating' => 'float',
        'multiFactorAuthenticationRating' => 'float',
        'domainVerificationRating' => 'float',
        'deploymentType' => '\EdGraph\PlatformClient\Model\TenantApiTenantV1DeploymentType',
        'branding' => '\EdGraph\PlatformClient\Model\TenantApiTenantV1TenantBrandingResponse'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'tenantId' => null,
        'tenantTypes' => null,
        'organizationIdentifier' => null,
        'organizationName' => null,
        'state' => null,
        'tenantStatus' => null,
        'isDemo' => null,
        'subscriptionsMigrated' => null,
        'subscriptions' => null,
        'domains' => null,
        'createdBy' => null,
        'createdDateTime' => null,
        'lastModifiedBy' => null,
        'lastModifiedDateTime' => null,
        'identityProviders' => null,
        'onboarding' => null,
        'organizations' => null,
        'organizationIdentifierHash' => null,
        'settings' => null,
        'additionalSettings' => null,
        'tenantType' => null,
        'securityScore' => 'double',
        'organizationalAccountRating' => 'double',
        'multiFactorAuthenticationRating' => 'double',
        'domainVerificationRating' => 'double',
        'deploymentType' => null,
        'branding' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'tenantId' => true,
        'tenantTypes' => true,
        'organizationIdentifier' => true,
        'organizationName' => true,
        'state' => true,
        'tenantStatus' => false,
        'isDemo' => false,
        'subscriptionsMigrated' => false,
        'subscriptions' => true,
        'domains' => true,
        'createdBy' => true,
        'createdDateTime' => true,
        'lastModifiedBy' => true,
        'lastModifiedDateTime' => true,
        'identityProviders' => true,
        'onboarding' => false,
        'organizations' => true,
        'organizationIdentifierHash' => true,
        'settings' => true,
        'additionalSettings' => false,
        'tenantType' => true,
        'securityScore' => true,
        'organizationalAccountRating' => true,
        'multiFactorAuthenticationRating' => true,
        'domainVerificationRating' => true,
        'deploymentType' => false,
        'branding' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tenantId' => 'tenantId',
        'tenantTypes' => 'tenantTypes',
        'organizationIdentifier' => 'organizationIdentifier',
        'organizationName' => 'organizationName',
        'state' => 'state',
        'tenantStatus' => 'tenantStatus',
        'isDemo' => 'isDemo',
        'subscriptionsMigrated' => 'subscriptionsMigrated',
        'subscriptions' => 'subscriptions',
        'domains' => 'domains',
        'createdBy' => 'createdBy',
        'createdDateTime' => 'createdDateTime',
        'lastModifiedBy' => 'lastModifiedBy',
        'lastModifiedDateTime' => 'lastModifiedDateTime',
        'identityProviders' => 'identityProviders',
        'onboarding' => 'onboarding',
        'organizations' => 'organizations',
        'organizationIdentifierHash' => 'organizationIdentifierHash',
        'settings' => 'settings',
        'additionalSettings' => 'additionalSettings',
        'tenantType' => 'tenantType',
        'securityScore' => 'securityScore',
        'organizationalAccountRating' => 'organizationalAccountRating',
        'multiFactorAuthenticationRating' => 'multiFactorAuthenticationRating',
        'domainVerificationRating' => 'domainVerificationRating',
        'deploymentType' => 'deploymentType',
        'branding' => 'branding'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tenantId' => 'setTenantId',
        'tenantTypes' => 'setTenantTypes',
        'organizationIdentifier' => 'setOrganizationIdentifier',
        'organizationName' => 'setOrganizationName',
        'state' => 'setState',
        'tenantStatus' => 'setTenantStatus',
        'isDemo' => 'setIsDemo',
        'subscriptionsMigrated' => 'setSubscriptionsMigrated',
        'subscriptions' => 'setSubscriptions',
        'domains' => 'setDomains',
        'createdBy' => 'setCreatedBy',
        'createdDateTime' => 'setCreatedDateTime',
        'lastModifiedBy' => 'setLastModifiedBy',
        'lastModifiedDateTime' => 'setLastModifiedDateTime',
        'identityProviders' => 'setIdentityProviders',
        'onboarding' => 'setOnboarding',
        'organizations' => 'setOrganizations',
        'organizationIdentifierHash' => 'setOrganizationIdentifierHash',
        'settings' => 'setSettings',
        'additionalSettings' => 'setAdditionalSettings',
        'tenantType' => 'setTenantType',
        'securityScore' => 'setSecurityScore',
        'organizationalAccountRating' => 'setOrganizationalAccountRating',
        'multiFactorAuthenticationRating' => 'setMultiFactorAuthenticationRating',
        'domainVerificationRating' => 'setDomainVerificationRating',
        'deploymentType' => 'setDeploymentType',
        'branding' => 'setBranding'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tenantId' => 'getTenantId',
        'tenantTypes' => 'getTenantTypes',
        'organizationIdentifier' => 'getOrganizationIdentifier',
        'organizationName' => 'getOrganizationName',
        'state' => 'getState',
        'tenantStatus' => 'getTenantStatus',
        'isDemo' => 'getIsDemo',
        'subscriptionsMigrated' => 'getSubscriptionsMigrated',
        'subscriptions' => 'getSubscriptions',
        'domains' => 'getDomains',
        'createdBy' => 'getCreatedBy',
        'createdDateTime' => 'getCreatedDateTime',
        'lastModifiedBy' => 'getLastModifiedBy',
        'lastModifiedDateTime' => 'getLastModifiedDateTime',
        'identityProviders' => 'getIdentityProviders',
        'onboarding' => 'getOnboarding',
        'organizations' => 'getOrganizations',
        'organizationIdentifierHash' => 'getOrganizationIdentifierHash',
        'settings' => 'getSettings',
        'additionalSettings' => 'getAdditionalSettings',
        'tenantType' => 'getTenantType',
        'securityScore' => 'getSecurityScore',
        'organizationalAccountRating' => 'getOrganizationalAccountRating',
        'multiFactorAuthenticationRating' => 'getMultiFactorAuthenticationRating',
        'domainVerificationRating' => 'getDomainVerificationRating',
        'deploymentType' => 'getDeploymentType',
        'branding' => 'getBranding'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('tenantId', $data ?? [], null);
        $this->setIfExists('tenantTypes', $data ?? [], null);
        $this->setIfExists('organizationIdentifier', $data ?? [], null);
        $this->setIfExists('organizationName', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
        $this->setIfExists('tenantStatus', $data ?? [], null);
        $this->setIfExists('isDemo', $data ?? [], null);
        $this->setIfExists('subscriptionsMigrated', $data ?? [], null);
        $this->setIfExists('subscriptions', $data ?? [], null);
        $this->setIfExists('domains', $data ?? [], null);
        $this->setIfExists('createdBy', $data ?? [], null);
        $this->setIfExists('createdDateTime', $data ?? [], null);
        $this->setIfExists('lastModifiedBy', $data ?? [], null);
        $this->setIfExists('lastModifiedDateTime', $data ?? [], null);
        $this->setIfExists('identityProviders', $data ?? [], null);
        $this->setIfExists('onboarding', $data ?? [], null);
        $this->setIfExists('organizations', $data ?? [], null);
        $this->setIfExists('organizationIdentifierHash', $data ?? [], null);
        $this->setIfExists('settings', $data ?? [], null);
        $this->setIfExists('additionalSettings', $data ?? [], null);
        $this->setIfExists('tenantType', $data ?? [], null);
        $this->setIfExists('securityScore', $data ?? [], null);
        $this->setIfExists('organizationalAccountRating', $data ?? [], null);
        $this->setIfExists('multiFactorAuthenticationRating', $data ?? [], null);
        $this->setIfExists('domainVerificationRating', $data ?? [], null);
        $this->setIfExists('deploymentType', $data ?? [], null);
        $this->setIfExists('branding', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tenantId
     *
     * @return string|null
     */
    public function getTenantId()
    {
        return $this->container['tenantId'];
    }

    /**
     * Sets tenantId
     *
     * @param string|null $tenantId tenantId
     *
     * @return self
     */
    public function setTenantId($tenantId)
    {
        if (is_null($tenantId)) {
            array_push($this->openAPINullablesSetToNull, 'tenantId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tenantId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tenantId'] = $tenantId;

        return $this;
    }

    /**
     * Gets tenantTypes
     *
     * @return \EdGraph\PlatformClient\Model\TenantApiTenantV1TenantType[]|null
     */
    public function getTenantTypes()
    {
        return $this->container['tenantTypes'];
    }

    /**
     * Sets tenantTypes
     *
     * @param \EdGraph\PlatformClient\Model\TenantApiTenantV1TenantType[]|null $tenantTypes tenantTypes
     *
     * @return self
     */
    public function setTenantTypes($tenantTypes)
    {
        if (is_null($tenantTypes)) {
            array_push($this->openAPINullablesSetToNull, 'tenantTypes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tenantTypes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tenantTypes'] = $tenantTypes;

        return $this;
    }

    /**
     * Gets organizationIdentifier
     *
     * @return string|null
     */
    public function getOrganizationIdentifier()
    {
        return $this->container['organizationIdentifier'];
    }

    /**
     * Sets organizationIdentifier
     *
     * @param string|null $organizationIdentifier organizationIdentifier
     *
     * @return self
     */
    public function setOrganizationIdentifier($organizationIdentifier)
    {
        if (is_null($organizationIdentifier)) {
            array_push($this->openAPINullablesSetToNull, 'organizationIdentifier');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('organizationIdentifier', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['organizationIdentifier'] = $organizationIdentifier;

        return $this;
    }

    /**
     * Gets organizationName
     *
     * @return string|null
     */
    public function getOrganizationName()
    {
        return $this->container['organizationName'];
    }

    /**
     * Sets organizationName
     *
     * @param string|null $organizationName organizationName
     *
     * @return self
     */
    public function setOrganizationName($organizationName)
    {
        if (is_null($organizationName)) {
            array_push($this->openAPINullablesSetToNull, 'organizationName');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('organizationName', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['organizationName'] = $organizationName;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string|null $state state
     *
     * @return self
     */
    public function setState($state)
    {
        if (is_null($state)) {
            array_push($this->openAPINullablesSetToNull, 'state');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('state', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets tenantStatus
     *
     * @return \EdGraph\PlatformClient\Model\TenantApiTenantV1TenantStatus|null
     */
    public function getTenantStatus()
    {
        return $this->container['tenantStatus'];
    }

    /**
     * Sets tenantStatus
     *
     * @param \EdGraph\PlatformClient\Model\TenantApiTenantV1TenantStatus|null $tenantStatus tenantStatus
     *
     * @return self
     */
    public function setTenantStatus($tenantStatus)
    {
        if (is_null($tenantStatus)) {
            throw new \InvalidArgumentException('non-nullable tenantStatus cannot be null');
        }
        $this->container['tenantStatus'] = $tenantStatus;

        return $this;
    }

    /**
     * Gets isDemo
     *
     * @return bool|null
     */
    public function getIsDemo()
    {
        return $this->container['isDemo'];
    }

    /**
     * Sets isDemo
     *
     * @param bool|null $isDemo isDemo
     *
     * @return self
     */
    public function setIsDemo($isDemo)
    {
        if (is_null($isDemo)) {
            throw new \InvalidArgumentException('non-nullable isDemo cannot be null');
        }
        $this->container['isDemo'] = $isDemo;

        return $this;
    }

    /**
     * Gets subscriptionsMigrated
     *
     * @return bool|null
     */
    public function getSubscriptionsMigrated()
    {
        return $this->container['subscriptionsMigrated'];
    }

    /**
     * Sets subscriptionsMigrated
     *
     * @param bool|null $subscriptionsMigrated subscriptionsMigrated
     *
     * @return self
     */
    public function setSubscriptionsMigrated($subscriptionsMigrated)
    {
        if (is_null($subscriptionsMigrated)) {
            throw new \InvalidArgumentException('non-nullable subscriptionsMigrated cannot be null');
        }
        $this->container['subscriptionsMigrated'] = $subscriptionsMigrated;

        return $this;
    }

    /**
     * Gets subscriptions
     *
     * @return \EdGraph\PlatformClient\Model\TenantApiTenantV1SubscriptionProfileResponse[]|null
     */
    public function getSubscriptions()
    {
        return $this->container['subscriptions'];
    }

    /**
     * Sets subscriptions
     *
     * @param \EdGraph\PlatformClient\Model\TenantApiTenantV1SubscriptionProfileResponse[]|null $subscriptions subscriptions
     *
     * @return self
     */
    public function setSubscriptions($subscriptions)
    {
        if (is_null($subscriptions)) {
            array_push($this->openAPINullablesSetToNull, 'subscriptions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('subscriptions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['subscriptions'] = $subscriptions;

        return $this;
    }

    /**
     * Gets domains
     *
     * @return \EdGraph\PlatformClient\Model\TenantApiTenantV1DomainProfileResponse[]|null
     */
    public function getDomains()
    {
        return $this->container['domains'];
    }

    /**
     * Sets domains
     *
     * @param \EdGraph\PlatformClient\Model\TenantApiTenantV1DomainProfileResponse[]|null $domains domains
     *
     * @return self
     */
    public function setDomains($domains)
    {
        if (is_null($domains)) {
            array_push($this->openAPINullablesSetToNull, 'domains');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('domains', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['domains'] = $domains;

        return $this;
    }

    /**
     * Gets createdBy
     *
     * @return string|null
     */
    public function getCreatedBy()
    {
        return $this->container['createdBy'];
    }

    /**
     * Sets createdBy
     *
     * @param string|null $createdBy createdBy
     *
     * @return self
     */
    public function setCreatedBy($createdBy)
    {
        if (is_null($createdBy)) {
            array_push($this->openAPINullablesSetToNull, 'createdBy');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('createdBy', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['createdBy'] = $createdBy;

        return $this;
    }

    /**
     * Gets createdDateTime
     *
     * @return string|null
     */
    public function getCreatedDateTime()
    {
        return $this->container['createdDateTime'];
    }

    /**
     * Sets createdDateTime
     *
     * @param string|null $createdDateTime createdDateTime
     *
     * @return self
     */
    public function setCreatedDateTime($createdDateTime)
    {
        if (is_null($createdDateTime)) {
            array_push($this->openAPINullablesSetToNull, 'createdDateTime');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('createdDateTime', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['createdDateTime'] = $createdDateTime;

        return $this;
    }

    /**
     * Gets lastModifiedBy
     *
     * @return string|null
     */
    public function getLastModifiedBy()
    {
        return $this->container['lastModifiedBy'];
    }

    /**
     * Sets lastModifiedBy
     *
     * @param string|null $lastModifiedBy lastModifiedBy
     *
     * @return self
     */
    public function setLastModifiedBy($lastModifiedBy)
    {
        if (is_null($lastModifiedBy)) {
            array_push($this->openAPINullablesSetToNull, 'lastModifiedBy');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('lastModifiedBy', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['lastModifiedBy'] = $lastModifiedBy;

        return $this;
    }

    /**
     * Gets lastModifiedDateTime
     *
     * @return string|null
     */
    public function getLastModifiedDateTime()
    {
        return $this->container['lastModifiedDateTime'];
    }

    /**
     * Sets lastModifiedDateTime
     *
     * @param string|null $lastModifiedDateTime lastModifiedDateTime
     *
     * @return self
     */
    public function setLastModifiedDateTime($lastModifiedDateTime)
    {
        if (is_null($lastModifiedDateTime)) {
            array_push($this->openAPINullablesSetToNull, 'lastModifiedDateTime');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('lastModifiedDateTime', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['lastModifiedDateTime'] = $lastModifiedDateTime;

        return $this;
    }

    /**
     * Gets identityProviders
     *
     * @return \EdGraph\PlatformClient\Model\TenantApiTenantV1TenantIdentityProviders[]|null
     */
    public function getIdentityProviders()
    {
        return $this->container['identityProviders'];
    }

    /**
     * Sets identityProviders
     *
     * @param \EdGraph\PlatformClient\Model\TenantApiTenantV1TenantIdentityProviders[]|null $identityProviders identityProviders
     *
     * @return self
     */
    public function setIdentityProviders($identityProviders)
    {
        if (is_null($identityProviders)) {
            array_push($this->openAPINullablesSetToNull, 'identityProviders');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('identityProviders', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['identityProviders'] = $identityProviders;

        return $this;
    }

    /**
     * Gets onboarding
     *
     * @return \EdGraph\PlatformClient\Model\TenantApiTenantV1Onboarding|null
     */
    public function getOnboarding()
    {
        return $this->container['onboarding'];
    }

    /**
     * Sets onboarding
     *
     * @param \EdGraph\PlatformClient\Model\TenantApiTenantV1Onboarding|null $onboarding onboarding
     *
     * @return self
     */
    public function setOnboarding($onboarding)
    {
        if (is_null($onboarding)) {
            throw new \InvalidArgumentException('non-nullable onboarding cannot be null');
        }
        $this->container['onboarding'] = $onboarding;

        return $this;
    }

    /**
     * Gets organizations
     *
     * @return \EdGraph\PlatformClient\Model\TenantApiTenantV1Organization[]|null
     */
    public function getOrganizations()
    {
        return $this->container['organizations'];
    }

    /**
     * Sets organizations
     *
     * @param \EdGraph\PlatformClient\Model\TenantApiTenantV1Organization[]|null $organizations organizations
     *
     * @return self
     */
    public function setOrganizations($organizations)
    {
        if (is_null($organizations)) {
            array_push($this->openAPINullablesSetToNull, 'organizations');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('organizations', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['organizations'] = $organizations;

        return $this;
    }

    /**
     * Gets organizationIdentifierHash
     *
     * @return string|null
     */
    public function getOrganizationIdentifierHash()
    {
        return $this->container['organizationIdentifierHash'];
    }

    /**
     * Sets organizationIdentifierHash
     *
     * @param string|null $organizationIdentifierHash organizationIdentifierHash
     *
     * @return self
     */
    public function setOrganizationIdentifierHash($organizationIdentifierHash)
    {
        if (is_null($organizationIdentifierHash)) {
            array_push($this->openAPINullablesSetToNull, 'organizationIdentifierHash');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('organizationIdentifierHash', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['organizationIdentifierHash'] = $organizationIdentifierHash;

        return $this;
    }

    /**
     * Gets settings
     *
     * @return \EdGraph\PlatformClient\Model\TenantApiTenantV1TenantSetting[]|null
     */
    public function getSettings()
    {
        return $this->container['settings'];
    }

    /**
     * Sets settings
     *
     * @param \EdGraph\PlatformClient\Model\TenantApiTenantV1TenantSetting[]|null $settings settings
     *
     * @return self
     */
    public function setSettings($settings)
    {
        if (is_null($settings)) {
            array_push($this->openAPINullablesSetToNull, 'settings');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('settings', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['settings'] = $settings;

        return $this;
    }

    /**
     * Gets additionalSettings
     *
     * @return \EdGraph\PlatformClient\Model\TenantApiTenantV1TenantAdditionalSetting|null
     */
    public function getAdditionalSettings()
    {
        return $this->container['additionalSettings'];
    }

    /**
     * Sets additionalSettings
     *
     * @param \EdGraph\PlatformClient\Model\TenantApiTenantV1TenantAdditionalSetting|null $additionalSettings additionalSettings
     *
     * @return self
     */
    public function setAdditionalSettings($additionalSettings)
    {
        if (is_null($additionalSettings)) {
            throw new \InvalidArgumentException('non-nullable additionalSettings cannot be null');
        }
        $this->container['additionalSettings'] = $additionalSettings;

        return $this;
    }

    /**
     * Gets tenantType
     *
     * @return string|null
     */
    public function getTenantType()
    {
        return $this->container['tenantType'];
    }

    /**
     * Sets tenantType
     *
     * @param string|null $tenantType tenantType
     *
     * @return self
     */
    public function setTenantType($tenantType)
    {
        if (is_null($tenantType)) {
            array_push($this->openAPINullablesSetToNull, 'tenantType');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tenantType', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tenantType'] = $tenantType;

        return $this;
    }

    /**
     * Gets securityScore
     *
     * @return float|null
     */
    public function getSecurityScore()
    {
        return $this->container['securityScore'];
    }

    /**
     * Sets securityScore
     *
     * @param float|null $securityScore securityScore
     *
     * @return self
     */
    public function setSecurityScore($securityScore)
    {
        if (is_null($securityScore)) {
            array_push($this->openAPINullablesSetToNull, 'securityScore');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('securityScore', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['securityScore'] = $securityScore;

        return $this;
    }

    /**
     * Gets organizationalAccountRating
     *
     * @return float|null
     */
    public function getOrganizationalAccountRating()
    {
        return $this->container['organizationalAccountRating'];
    }

    /**
     * Sets organizationalAccountRating
     *
     * @param float|null $organizationalAccountRating organizationalAccountRating
     *
     * @return self
     */
    public function setOrganizationalAccountRating($organizationalAccountRating)
    {
        if (is_null($organizationalAccountRating)) {
            array_push($this->openAPINullablesSetToNull, 'organizationalAccountRating');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('organizationalAccountRating', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['organizationalAccountRating'] = $organizationalAccountRating;

        return $this;
    }

    /**
     * Gets multiFactorAuthenticationRating
     *
     * @return float|null
     */
    public function getMultiFactorAuthenticationRating()
    {
        return $this->container['multiFactorAuthenticationRating'];
    }

    /**
     * Sets multiFactorAuthenticationRating
     *
     * @param float|null $multiFactorAuthenticationRating multiFactorAuthenticationRating
     *
     * @return self
     */
    public function setMultiFactorAuthenticationRating($multiFactorAuthenticationRating)
    {
        if (is_null($multiFactorAuthenticationRating)) {
            array_push($this->openAPINullablesSetToNull, 'multiFactorAuthenticationRating');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('multiFactorAuthenticationRating', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['multiFactorAuthenticationRating'] = $multiFactorAuthenticationRating;

        return $this;
    }

    /**
     * Gets domainVerificationRating
     *
     * @return float|null
     */
    public function getDomainVerificationRating()
    {
        return $this->container['domainVerificationRating'];
    }

    /**
     * Sets domainVerificationRating
     *
     * @param float|null $domainVerificationRating domainVerificationRating
     *
     * @return self
     */
    public function setDomainVerificationRating($domainVerificationRating)
    {
        if (is_null($domainVerificationRating)) {
            array_push($this->openAPINullablesSetToNull, 'domainVerificationRating');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('domainVerificationRating', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['domainVerificationRating'] = $domainVerificationRating;

        return $this;
    }

    /**
     * Gets deploymentType
     *
     * @return \EdGraph\PlatformClient\Model\TenantApiTenantV1DeploymentType|null
     */
    public function getDeploymentType()
    {
        return $this->container['deploymentType'];
    }

    /**
     * Sets deploymentType
     *
     * @param \EdGraph\PlatformClient\Model\TenantApiTenantV1DeploymentType|null $deploymentType deploymentType
     *
     * @return self
     */
    public function setDeploymentType($deploymentType)
    {
        if (is_null($deploymentType)) {
            throw new \InvalidArgumentException('non-nullable deploymentType cannot be null');
        }
        $this->container['deploymentType'] = $deploymentType;

        return $this;
    }

    /**
     * Gets branding
     *
     * @return \EdGraph\PlatformClient\Model\TenantApiTenantV1TenantBrandingResponse|null
     */
    public function getBranding()
    {
        return $this->container['branding'];
    }

    /**
     * Sets branding
     *
     * @param \EdGraph\PlatformClient\Model\TenantApiTenantV1TenantBrandingResponse|null $branding branding
     *
     * @return self
     */
    public function setBranding($branding)
    {
        if (is_null($branding)) {
            throw new \InvalidArgumentException('non-nullable branding cannot be null');
        }
        $this->container['branding'] = $branding;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


