<?php
/**
 * ValidationsApiCoreV1Provider
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace EdGraph\PlatformClient\Model;
use \EdGraph\PlatformClient\ObjectSerializer;

/**
 * ValidationsApiCoreV1Provider Class Doc Comment
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ValidationsApiCoreV1Provider
{
    /**
     * Possible values of this enum
     */
    public const UNKNOWN = 'Unknown';

    public const EDGRAPH = 'Edgraph';

    public const TEXAS_EDUCATION_EXCHANGE = 'TexasEducationExchange';

    public const TEXAS_EDUCATION_AGENCY = 'TexasEducationAgency';

    public const OPEN_EDUCATION_ANALYTICS = 'OpenEducationAnalytics';

    public const EXTERNAL = 'External';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::EDGRAPH,
            self::TEXAS_EDUCATION_EXCHANGE,
            self::TEXAS_EDUCATION_AGENCY,
            self::OPEN_EDUCATION_ANALYTICS,
            self::EXTERNAL
        ];
    }
}


