<?php
/**
 * EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EdGraph\PlatformClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequestTest Class Doc Comment
 *
 * @category    Class
 * @description EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest
 * @package     EdGraph\PlatformClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest"
     */
    public function testEdfiAdminApiEdfiAdminV1SyncLocalEducationAgencyRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tenantId"
     */
    public function testPropertyTenantId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "instanceId"
     */
    public function testPropertyInstanceId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "year"
     */
    public function testPropertyYear()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "edOrgId"
     */
    public function testPropertyEdOrgId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "edOrgGuid"
     */
    public function testPropertyEdOrgGuid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "entries"
     */
    public function testPropertyEntries()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "assignToExistingApplications"
     */
    public function testPropertyAssignToExistingApplications()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
