<?php
/**
 * IMSAdminApiV1ClientsClientCreatedResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EdGraph\PlatformClient\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * IMSAdminApiV1ClientsClientCreatedResponseTest Class Doc Comment
 *
 * @category    Class
 * @description IMSAdminApiV1ClientsClientCreatedResponse
 * @package     EdGraph\PlatformClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class IMSAdminApiV1ClientsClientCreatedResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "IMSAdminApiV1ClientsClientCreatedResponse"
     */
    public function testIMSAdminApiV1ClientsClientCreatedResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tenantId"
     */
    public function testPropertyTenantId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "applicationId"
     */
    public function testPropertyApplicationId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "clientId"
     */
    public function testPropertyClientId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
