<?php
/**
 * UsersEducationOrganizationsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EdGraph\PlatformClient\Test\Api;

use \EdGraph\PlatformClient\Configuration;
use \EdGraph\PlatformClient\ApiException;
use \EdGraph\PlatformClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UsersEducationOrganizationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UsersEducationOrganizationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addUserEducationOrganization
     *
     * Adds an Education Organization to a user..
     *
     */
    public function testAddUserEducationOrganization()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserEducationOrganizations
     *
     * Gets the Education Organizations of a user..
     *
     */
    public function testGetUserEducationOrganizations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for removeUserEducationOrganization
     *
     * Removes an Education Organization from a user..
     *
     */
    public function testRemoveUserEducationOrganization()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateUserEducationOrganization
     *
     * Updates the Education Organization of a user..
     *
     */
    public function testUpdateUserEducationOrganization()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
