<?php
/**
 * UsersLicensesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * All Api
 *
 * All Api- v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EdGraph\PlatformClient\Test\Api;

use \EdGraph\PlatformClient\Configuration;
use \EdGraph\PlatformClient\ApiException;
use \EdGraph\PlatformClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UsersLicensesApiTest Class Doc Comment
 *
 * @category Class
 * @package  EdGraph\PlatformClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UsersLicensesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for assignLicenseTenantUserAsync
     *
     * Assigns a license to a user in the context of a specific tenant.
     *
     */
    public function testAssignLicenseTenantUserAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for assignLicenseTenantUserBulkAsync
     *
     * Assigns one or more licenses to a user in the context of a specific tenant.
     *
     */
    public function testAssignLicenseTenantUserBulkAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAllTenantUserApplicationLicensesAsync
     *
     * Retrieves a list of user licenses in the context of a specific tenant.
     *
     */
    public function testGetAllTenantUserApplicationLicensesAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for revokeLicenseTenantUserAsync
     *
     * Revokes a license from a user in the context of a specific tenant.
     *
     */
    public function testRevokeLicenseTenantUserAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for revokeLicenseTenantUserBulkAsync
     *
     * Revokes one or more licenses from a user in the context of a specific tenant.
     *
     */
    public function testRevokeLicenseTenantUserBulkAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
